spring:
  datasource:
    url: jdbc:mysql://localhost:3306/htmx
    username: root
    password: NewPassword
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#    to change base url of the backend